version: '3.3'

services:
   # Postgres
    db:
        image: postgres
        restart: 'always'
        environment:
            - POSTGRES_USER=casepro
            - POSTGRES_PASSWORD=nyaruka
            - POSTGRES_DB=casepro
        build: './db'
        volumes:
            - .:/data
        ports:
            - "5432:5432"
    web:
        build: .
        command: ["./run_web.sh"]
        volumes:
            - .:/data
        ports:
            - "8000:8000"
        links:
            - db
        depends_on:
            - db

